seed: 42
device: cuda
dataset:
  name: ShapeNetAD
  dataset_dir: /path/to/Anomaly-ShapeNet-v2/dataset/16384
  cls_name: [ 
    "ashtray0","bag0","bottle0","bottle1","bottle3","bowl0",
    "bowl1","bowl2","bowl3","bowl4","bowl5","bucket0",
    "bucket1","cap0","cap3","cap4","cap5","cup0",
    "cup1","eraser0","headset0","headset1","helmet0","helmet1",
    "helmet2","helmet3","jar0","microphone0","shelf0","tap0",
    "tap1","vase0","vase1","vase2","vase3","vase4",
    "vase5","vase7","vase8","vase9"
    ]
  normalize: False
  scale_factor: 1.0
  template_path: data/ShapeNetAD

infer:
  batch_size: 1
  num_workers: 0
  voxel_size: 0.03
  top_k: 1
  shuffle: False
  cd_threshold: 1.6
  checkpoint_path: results/ShapeNetAD/runs_sdf/
  output_dir: results/ShapeNetAD/runs_sdf/outputs
  settings_path: results/ShapeNetAD/runs_sdf/settings.yaml